model:
  network:
    name: RFR
    head_name: ResUNet

dataset:
  name: NUDT-MIRSDT  # [MIST, NUDT-MIRSDT]
  root: ./data/NUDT-MIRSDT  # data root path
  full_supervision: True

test:
  exp_root: /media/kou/Data1/gr/Deep-MIST/results/ResUNet_RFR_NUDTMIRSDT/20250524_013108/
  num_workers: 16  # number of data loading workers
  checkpoint: /media/kou/Data1/gr/Deep-MIST/results/ResUNet_RFR_NUDTMIRSDT/20250524_013108/checkpoints/model_epoch_14.pth