model:
  network:
    name: LS_STDNet

dataset:
  name: NUDT-MIRSDT  # [MIST, NUDT-MIRSDT]
  root: /home/ubuntu/data/zhengqinxu/object_detection/Deep-MIST/data/NUDT-MIRSDT  # data root path
  full_supervision: True

test:
  exp_root: /home/ubuntu/data/zhengqinxu/object_detection/Deep-MIST/results/LS_STDNet_MIST_0219_PANLSAGGDecoder_L7S5ParaLoss/NUDT_Test # test results save root
  num_workers: 16  # number of data loading workers
  checkpoint: /home/ubuntu/data/zhengqinxu/object_detection/Deep-MIST/results/LS_STDNet_NUDTMIRSDT_0327_71/20260327_133319/checkpoints/model_epoch_45.pth