model:
  network:
    name: ISNet

dataset:
  name: MIST  # [MIST, NUDT-MIRSDT]
  root: ./data/MIST_0912  # data root path
  num_inputs: 5  # number of input frames
  img_size: [ 384, 384 ]  # image size
  frame_padding: False
  data_aug: # data augmentation options
    random_flip: True
    random_crop: True
    random_rotation: True
    color_enhance: False
    random_peper: False

test:
  exp_root: /media/kou/Data2/gaorui/Deep-MIST/results_new/ISNet/
  num_workers: 16  # number of data loading workers
  checkpoint: /media/kou/Data2/gaorui/Deep-MIST/results_new/ISNet/model_epoch_41.pth