model:
  network:
    name: RDIAN

dataset:
  name: NUDT-MIRSDT  # [MIST, NUDT-MIRSDT]
  root: ./data/NUDT-MIRSDT  # data root path
  full_supervision: True

test:
  exp_root: /media/kou/Data1/gr/Deep-MIST/results/RDIAN_NUDTMIRSDT/20240516_014019/
  num_workers: 16  # number of data loading workers
  checkpoint: /media/kou/Data1/gr/Deep-MIST/results/RDIAN_NUDTMIRSDT/20240516_014019/checkpoints/model_epoch_50.pth